### ISSUE TITLE
Missing m.npy and n.npy

### ISSUE THREAD

**Issue by sshahhos** [htqin/DSG#2]
I'm getting the following error and it seems the repo is missing two ".npy" files.

Training is terminating due to exception: [Errno 2] No such file or directory: './m_n_perc/m.npy'
Traceback (most recent call last):
  File "quantization_aware_training/main.py", line 340, in run
    train_error, train_loss, train5_error = self.trainer.train(epoch=epoch)
  File "quantization_aware_training/trainer.py", line 264, in train
    m = np.load('./m_n_perc/m.npy', allow_pickle = True)
...
FileNotFoundError: [Errno 2] No such file or directory: './m_n_perc/m.npy'

**Comment by ghw1113** [comment]
Yes, I have also encountered such a problem
